export const DATABASE_IDS = {
  CORE: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_CORE_ID!,
  USERS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_USERS_ID!,
  COURSES: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_COURSES_ID!,
  INSTITUTIONS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_INSTITUTIONS_ID!,
  AI: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_AI_ID!,
  ANALYTICS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ANALYTICS_ID!,
  INTEGRATIONS: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_INTEGRATIONS_ID!,
  WEB3: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_WEB3_ID!,
};

export const COLLECTION_IDS = {
  // Core Collections
  SETTINGS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_SETTINGS_ID!,
  ROLES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ROLES_ID!,
  
  // User Collections
  USERS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USERS_ID!,
  USER_PROFILES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_USER_PROFILES_ID!,
  
  // Course Collections
  COURSES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_COURSES_ID!,
  MODULES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_MODULES_ID!,
  LESSONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_LESSONS_ID!,
  ENROLLMENTS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ENROLLMENTS_ID!,
  ASSESSMENTS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ASSESSMENTS_ID!,
  SUBMISSIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_SUBMISSIONS_ID!,
  
  // Institution Collections
  INSTITUTIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_INSTITUTIONS_ID!,
  INSTITUTION_INTEGRATIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_INSTITUTION_INTEGRATIONS_ID!,
  
  // AI Collections
  AI_MODELS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_AI_MODELS_ID!,
  AI_RECOMMENDATIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_AI_RECOMMENDATIONS_ID!,
  
  // Analytics Collections
  EVENTS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_EVENTS_ID!,
  METRICS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_METRICS_ID!,
  
  // Integration Collections
  EXTERNAL_INTEGRATIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_EXTERNAL_INTEGRATIONS_ID!,
  
  // Web3 Collections
  WALLETS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_WALLETS_ID!,
  TRANSACTIONS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_TRANSACTIONS_ID!,
  CERTIFICATES: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CERTIFICATES_ID!,
  NFT_CONTRACTS: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_NFT_CONTRACTS_ID!,
};

export const STORAGE_IDS = {
  AVATARS: process.env.NEXT_PUBLIC_APPWRITE_STORAGE_AVATARS_ID!,
  COURSE_MEDIA: process.env.NEXT_PUBLIC_APPWRITE_STORAGE_COURSE_MEDIA_ID!,
  CERTIFICATES: process.env.NEXT_PUBLIC_APPWRITE_STORAGE_CERTIFICATES_ID!,
};